list.files(pattern = "Rmd")
list.files(pattern = "html")
library(rmarkdown)
library(bslib)
rmarkdown::render_site("index.Rmd")
rmarkdown::render_site("about.Rmd")
rmarkdown::render_site("misc.Rmd")
rmarkdown::render_site("boxplot.Rmd")
rmarkdown::render_site("rants.Rmd")
rmarkdown::render_site("code.Rmd")
rmarkdown::render_site("social.Rmd")
rmarkdown::render_site("work.Rmd")
rmarkdown::render_site("pulse.Rmd")
rmarkdown::render_site("vegan.Rmd")
rmarkdown::render_site("Rmaps.Rmd")
rmarkdown::render_site("profiles.Rmd")
rmarkdown::render_site("rectgrid.Rmd")
rmarkdown::render_site("testpage.Rmd")
